#!/usr/bin/env python3
"""English-code quality rules for the funnel bottom (ae L0/L1 hardening, fb 2026-09-16).

    python3 datagen/code_quality_rules.py --selftest

WHY A SEPARATE MODULE. The 2026-09-16 six-domain audit (runs/l0_code_funnel_audit_0916.md)
measured the candidate Gopher text rules against the real code corpora and hand-read their
positives. Three of the four text rules FALSE-KILL real code and are deliberately NOT here:

  - dup_lines<0.7 (web tier): positives are unit tests with repeated asserts, docstring
    triple-quote separators and `Args:` lines, repeated decorators -- high-value code.
    6-15% trigger rate.
  - all-stub-functions: positives are zope.interface/ABC/Protocol declarations and .pyi
    micropython stubs -- real interface code.
  - long no-punctuation line / "minified" shape: on code domains the positives are module
    docstrings, comments, MIT licenses, and (l3_noexec) dense English problem prose.

The one rule that survives is a STRICT machine-generated-banner detector. The volume is real
(starcoder 2.55%, rp1t 0.66%, ~0 elsewhere) and every positive hand-read was a Django
migration or an AutoRest/protobuf SDK file. Machine-generated files are near-duplicate by
construction and the lexical dedup cannot cluster every rename, so the banner is the reliable
signal.

PLACEMENT. Like code_lang_validate: beside the builders, NOT in filters/PIPELINE_FILTERS. A
build that calls it records module_sha256 in its own stats; no existing frozen domain's
filters_fp moves. Callers decide what to do with the verdict (drop / tag) -- this module only
classifies, it never edits a corpus.
"""
import argparse
import hashlib
import os
import re

#: A line that says the file was produced. Necessary but not sufficient on its own: real code
#: uses "generated" as an ordinary word ("rows generated by the iterator", "generated_for").
_MARK = re.compile(
    r"(?i)auto[- ]?generated|generated\s+by|automatically\s+generated|"
    r"this\s+(?:file|code)\s+is\s+(?:auto[- ]?)?generated|@generated\b"
)

#: A machine/tool generator, or an explicit do-not-edit instruction. "do not edit" alone is
#: NOT sufficient (real code has "# do not modify the cache key"); it must co-occur with a
#: _MARK in the same header, which the MARK-and-TOOLS conjunction enforces.
_TOOLS = re.compile(
    r"(?i)protoc(?:ol buffer)?|protobuf|django|autorest|swagger|openapi|thrift|grpc|"
    r"cython|jinja|yacc|lex\b|swig|pb2\b|code generator|generated code|"
    r"do\s+not\s+(?:edit|modify|delete)"
)

_COMMENT_PREFIX = ("#", "//", "/*", "*", '"""', "'''")


def module_sha256(path=None):
    """Content hash of this file, same basis filters_fp uses, so a build can stamp its producer."""
    p = path or os.path.abspath(__file__)
    with open(p, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:16]


def leading_header(text):
    """The leading comment block and/or module docstring; stops at the first code line.

    Restricting the banner to the header is the load-bearing discrimination: an inline
    `x = generated_by_cache  # do not modify` and an in-function docstring must not count.
    """
    out = []
    in_doc = False
    quote = '"""'
    for line in text.split("\n"):
        s = line.strip()
        if not s:
            continue
        if in_doc:
            out.append(s)
            if quote in s:
                in_doc = False
            continue
        if s[:3] in ('"""', "'''"):
            quote = s[:3]
            out.append(s)
            in_doc = s.count(quote) < 2
            continue
        if s.startswith(_COMMENT_PREFIX):
            out.append(s)
            continue
        break
    return "\n".join(out)


def is_autogen_banner(text):
    """True only when the LEADING header carries both a generated-marker and a tool/do-not-edit.

    Known-answer positives are real Django/AutoRest/protobuf banners; negatives are real code
    that merely uses the words. Asserted in --selftest against the exact false-fires found by
    hand-reading: `autogenerated = False`, an inline `# do not modify the cache`, and an
    in-function docstring "rows generated by the iterator".
    """
    header = leading_header(text)
    return bool(_MARK.search(header) and _TOOLS.search(header))


# ---------------------------------------------------------------------------------------
# Known answers. 7 positive machine banners, 7 real-code negatives. Each negative is a
# document a looser regex (or a whole-text search) was measured to false-kill.
_KA_AUTOGEN = [
    # --- positives: genuine machine-generated leading banners ---
    ("# Code generated by Microsoft (R) AutoRest Code Generator.\n"
     "# Changes may cause incorrect behavior.\n\nfrom x import Y\n", True),
    ("# Generated by Django 3.1.1 on 2020-09-01 17:04\n\n"
     "from django.db import migrations\n", True),
    ("// Generated by the protocol buffer compiler.  DO NOT EDIT!\n\n#include <stdio.h>\n", True),
    ('"""This file is automatically generated by swagger. Do not edit."""\n\nimport os\n', True),
    ("# AUTO-GENERATED by a code generator -- do not modify this file.\n\nx = 1\n", True),
    ("# @generated from protobuf -- do not delete\n\npackage foo\n", True),
    ("# -*- coding: utf-8 -*-\n# Generated by Django 1.9 on 2015-12-21 12:22\n\n"
     "from django.db import models\n", True),
    # --- negatives: real code that a looser rule eats ---
    ("# this generator yields values lazily\n\n"
     "def gen(n):\n    for i in range(n):\n        yield n\n", False),
    ("autogenerated = False\nprint(autogenerated)\n", False),
    ("x = generated_by_cache  # do not modify the cache key at runtime\n", False),
    ("# do not modify the cache key at runtime\n\ndef f():\n    return 1\n", False),
    ("def f():\n    '''Rows generated by the iterator.'''\n    return rows\n", False),
    ("# Permission is hereby granted, free of charge, to deal in the Software.\n\ndef f():\n    return 1\n", False),
    ("# Hand-written helper; generated for the sprint demo.\ndef f():\n    return 1\n", False),
]


def _selftest():
    assert len(_KA_AUTOGEN) == 14, len(_KA_AUTOGEN)
    npos = sum(1 for _, want in _KA_AUTOGEN if want)
    nneg = len(_KA_AUTOGEN) - npos
    assert npos == 7 and nneg == 7, (npos, nneg)
    fails = []
    for i, (text, want) in enumerate(_KA_AUTOGEN):
        got = is_autogen_banner(text)
        if got != want:
            fails.append(f"[{i}] want {want}, got {got} :: {text.splitlines()[0][:60]!r}")
    # The header gate itself: a banner phrase on a NON-leading line must not fire even though
    # _MARK and _TOOLS both match -- this is the inline-cache false-kill at the rule level.
    inline = "import os\n\nx = 1  # auto-generated by django, do not edit\n"
    if is_autogen_banner(inline):
        fails.append("banner on a non-leading code line fired; the header gate is off")
    # The conjunction: a marker with no tool, and a tool with no marker, each must stay negative.
    if is_autogen_banner("# generated for the sprint demo\nx=1\n"):
        fails.append("marker without a tool fired")
    if is_autogen_banner("# django migrations are useful\nx=1\n"):
        fails.append("tool name without a generated-marker fired")
    if fails:
        print("FAIL\n" + "\n".join(fails))
        raise SystemExit(1)
    print(f"code_quality_rules selftest ok: {npos} banner positives + {nneg} real-code negatives")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        _selftest()
    else:
        ap.print_help()
