#!/usr/bin/env python3
"""The eval holdout, as a hash set every data path must exclude.

`python datagen/holdout.py` regenerates data/eval/holdout_hashes.txt from the eval
files; importers use `is_holdout(question)`.

Fail-closed: the hash file carries a fingerprint of the eval files that produced
it. is_holdout() RAISES if the file is missing, predates fingerprints, or is
stale (an eval file changed since regeneration). A guard that silently returns
False is indistinguishable from no guard at all -- the 2026-08-30 sft_all.pt
contamination (19/20 holdout questions packed because the hash set was empty)
is the reason this is loud, not silent.

# restartable: main() accumulates one hash set and writes HASH_PATH once, which the
# restartability check flags -- correctly, as a shape. It is cheap here and the reason is
# measurable rather than asserted: the whole registry is 13 files and ~31,000 rows of sha1 over
# short strings, a few seconds, and the output is a single derived file that is regenerated by
# re-running the command with no state to resume. A partial write is also impossible to
# mistake for a good one: the file leads with `# fp:<fingerprint>` and load() RAISES on a
# fingerprint mismatch, so an interrupted run leaves a file the next reader refuses rather than
# a short hash set it silently trusts.
"""

import hashlib
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class UnregisteredEval(KeyError):
    """A name no registry entry covers. Raised rather than returning a path, so an eval
    file cannot be scored before it is registered."""


# THE POPULATION, not a list of four paths. The four-entry EVAL_FILES was correct on its own
# population and its population was the wrong one: data/sft/control_sft_text_heldout.jsonl was
# not in it, so no corpus builder ever excluded it, and 2,114 of 7,523 measurable held-out
# items reached the pretraining corpus with this guard green, fingerprinted and loud
# (facts/contamination.json#cont.heldout_in_pretrain_corpus, e1, 2026-09-04).
#
# COUNTED ON THE POD, because `data/` is gitignored: a laptop glob plus a code grep found 8
# unregistered files and missed 3 that exist only on the pod and are loaded by paths built at
# runtime (gsm8k_zh_holdout, lambada_zh_src, math_hard_eval_v2_1k_fmt). 10, not 8 -- and the
# instrument, not the reasoning, is what differed (de, 2026-09-04).
#
# `question_field` IS A LIST, and may be None. These files disagree on the field name --
# question / instruction / prompt / text / content -- so a registry assuming one name would
# register a file and hash NOTHING from it: a silent no-op under a green check, the same
# failure class as the bug this fixes (e1's point). None is for a file whose leak surface is
# not a question at all, and it REQUIRES a `why` saying what the surface is: without that,
# None becomes the value someone reaches for when they have not looked, and the registry
# records "no question here" where it means "nobody checked".
REGISTRY = {
    "math_test_500": {
        "path": "data/eval/math_test_500.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-08-30",
        "why": "math-500, the metric of record for math; 0.0% contamination on the pod corpus",
    },
    "math_hard_eval_1k": {
        "path": "data/synthetic/math_hard_eval_1k.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-08-30",
        "why": "math-hard v1, retired as a metric (our own generators contaminated it) but still held out",
    },
    "code_holdout_500": {
        "path": "data/eval/code_holdout_500.jsonl",
        "kind": "heldout",
        "question_field": ["instruction"],
        "added": "2026-08-30",
        "why": "code holdout v1",
    },
    "code_holdout_v2_500": {
        "path": "data/eval/code_holdout_v2_500.jsonl",
        "kind": "heldout",
        "question_field": ["instruction"],
        "added": "2026-08-30",
        "why": "code holdout v2",
    },
    "control_sft_text_heldout": {
        "path": "data/sft/control_sft_text_heldout.jsonl",
        "kind": "heldout",
        "question_field": ["question"],
        "added": "2026-09-04",
        "why": "THE FILE THAT WAS MISSING: the control comparison's held-out set, 10,641 rows, "
               "read by eval_heldout.py and six e1_2x scripts. Its absence from the old "
               "four-entry list is why 1,199 held-out rows entered chatml/chat_qa verbatim",
    },
    "humaneval_164": {
        "path": "data/eval/humaneval/humaneval_164.jsonl",
        "kind": "gold",
        "question_field": ["prompt"],
        "added": "2026-09-04",
        "why": "HumanEval, 164 rows, the gold BPB metric's source. build_control_sft_text.py has "
               "an explicit check_no_eval_leak for it, so the SFT path was guarded and no "
               "corpus builder was -- the guarded-in-one-place case",
    },
    "gsm8k_zh_holdout": {
        "path": "data/eval/gsm8k_zh_holdout.jsonl",
        "kind": "heldout",
        "question_field": ["instruction"],
        "added": "2026-09-04",
        "why": "7,473 rows, NOT dead: it is the canary of "
               "facts/contamination.json#cont.gsm8k_zh_webhq_scan (status=measured), which names "
               "this exact path in its config.holdout. datagen/prepare_sft.py reads the "
               "non-holdout sibling data/gsm8k_zh.jsonl as an SFT source, so the pair is the "
               "shape that leaks if the exclusion was never wired",
    },
    "math_hard_eval_v2_1k": {
        "path": "data/synthetic/math_hard_eval_v2_1k.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-09-04",
        "why": "math-hard v2, 1,080 rows; read by scan_eval_golds and scan_math_contamination",
    },
    "math_hard_eval_v2_1k_fmt": {
        "path": "data/synthetic/math_hard_eval_v2_1k_fmt.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-09-04",
        "why": "the reformatted copy of v2_1k, same 1,080 questions. Registered separately "
               "because norm() is whitespace-insensitive but not format-insensitive, and a "
               "pod-only file loaded by a runtime path is exactly what the laptop glob missed",
    },
    "math_hard_eval_v2_5k": {
        "path": "data/synthetic/math_hard_eval_v2_5k.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-09-04",
        "why": "math-hard v2 5k, 3,161 rows; read by eval/math_v2_like.py",
    },
    "lambada_en": {
        "path": "data/eval/lambada_en/lambada_test_en.jsonl",
        "kind": "eval",
        "question_field": ["text"],
        "added": "2026-09-04",
        "why": "LAMBADA en, 5,153 rows. `text` is the whole passage including the target word, "
               "so hashing it covers the passage; a corpus copy of the passage IS the leak",
    },
    "lambada_zh": {
        "path": "data/eval/lambada_zh.jsonl",
        "kind": "eval",
        "question_field": None,
        "added": "2026-09-04",
        "why": "NO QUESTION FIELD, and this is measured rather than assumed: the rows carry "
               "context / target / distractor / target_id / src. The leak surface is the "
               "passage plus its target word, not a question, and it may need a different hash "
               "unit than qhash(question) -- context alone would register a field name that "
               "means something different per row. UNCOVERED by the hash set until that unit "
               "is decided; registered so the completeness check sees it and nobody reads its "
               "absence as 'not an eval file'",
    },
    "lambada_zh_src": {
        "path": "data/eval/holdout_v2/lambada_zh_src.jsonl",
        "kind": "eval",
        "question_field": None,
        "added": "2026-09-04",
        "why": "523 rows keyed `content`, the source passages lambada_zh was cut from. Same "
               "undecided hash unit as lambada_zh: `content` is a passage, not a question. "
               "Pod-only, found by counting on the pod rather than globbing the laptop",
    },
}

# Registry names whose file is expected to be absent here: named in code, on no disk we have.
# Kept as entries rather than deleted so `eval_path` still resolves them and the completeness
# check's reverse direction (an entry whose path is gone) does not fire on a known state.
KNOWN_ABSENT = {"ceval", "code_rp1t_handread50"}


def _validate_registry(reg=None):
    """Every entry is well formed, and a None question_field carries its reason.

    Called at import: a malformed entry must fail before anything reads the guard, not at the
    first hash. The None check is the load-bearing one -- without it None is the value someone
    reaches for when they have not looked, and the registry records "no question here" where it
    means "nobody checked" (e1's ruling, 2026-09-04).
    """
    reg = REGISTRY if reg is None else reg
    for name, e in sorted(reg.items()):
        for key in ("path", "kind", "question_field", "added", "why"):
            if key not in e:
                raise ValueError(f"registry entry {name!r} is missing {key!r}")
        if e["kind"] not in ("eval", "heldout", "gold"):
            raise ValueError(f"registry entry {name!r} has kind {e['kind']!r}, "
                             "not one of eval/heldout/gold")
        qf = e["question_field"]
        if qf is not None and not (isinstance(qf, list) and qf and all(isinstance(x, str) for x in qf)):
            raise ValueError(f"registry entry {name!r}: question_field must be a non-empty "
                             f"list of field names, or None with a why; got {qf!r}")
        if not str(e.get("why", "")).strip():
            raise ValueError(f"registry entry {name!r} has an empty why")
        if qf is None and len(str(e["why"]).strip()) < 40:
            raise ValueError(
                f"registry entry {name!r} has question_field None and a why too short to say "
                f"what its leak surface IS. None must be a measurement, not a default"
            )


_validate_registry()


def eval_path(name):
    """The absolute path of a registered eval file. Raises on an unregistered name.

    This is the enforcement: a loader that builds its own os.path.join can score a file the
    holdout guard has never heard of, which is how ten eval files sat outside the population.
    """
    e = REGISTRY.get(name)
    if e is None:
        raise UnregisteredEval(
            f"{name!r} is not in datagen/holdout.py REGISTRY. An eval file must be registered "
            f"before it is loaded, or the corpus builders cannot exclude it. Registered: "
            f"{sorted(REGISTRY)}"
        )
    return os.path.join(ROOT, e["path"])


# EVAL_FILES is a DERIVED VIEW, so nothing reads a bare list any more. Kept as a name because
# scripts/harness.py:4231 mirrors it and readers exist; it is now every registry entry that
# contributes hashes, not four hardcoded paths.
EVAL_FILES = [os.path.join(ROOT, e["path"]) for e in REGISTRY.values()]
HASH_PATH = os.path.join(ROOT, "data", "eval", "holdout_hashes.txt")


def norm(q):
    """Whitespace- and punctuation-insensitive key, so a reformatted copy still matches."""
    return "".join(ch for ch in str(q) if not ch.isspace() and ch not in "：:，,。.、（）()")


def qhash(q):
    return hashlib.sha1(norm(q).encode("utf-8")).hexdigest()[:16]


def _fingerprint():
    """sha1 of (basename, file-sha1) for every existing EVAL_FILES entry. Changes
    when an eval file is added, removed, or edited -- which is exactly when the
    hash set must be regenerated."""
    h = hashlib.sha1()
    for path in sorted(EVAL_FILES):
        if os.path.exists(path):
            h.update(os.path.basename(path).encode())
            h.update(hashlib.sha1(open(path, "rb").read()).digest())
    return h.hexdigest()[:16]


def load():
    if not os.path.exists(HASH_PATH):
        raise RuntimeError(
            f"{HASH_PATH} missing -- the holdout guard is unloaded. "
            "Run `python datagen/holdout.py` to regenerate."
        )
    lines = [l.strip() for l in open(HASH_PATH, encoding="utf-8") if l.strip()]
    fp = next((l[5:] for l in lines if l.startswith("# fp:")), None)
    if fp is None:
        raise RuntimeError(
            f"{HASH_PATH} has no fingerprint (old format) -- the guard may be stale. "
            "Run `python datagen/holdout.py` to regenerate."
        )
    if fp != _fingerprint():
        raise RuntimeError(
            f"{HASH_PATH} is stale: eval files changed since it was generated. "
            "Run `python datagen/holdout.py` to regenerate."
        )
    return {l for l in lines if not l.startswith("#")}


_CACHE = None


def is_holdout(q):
    global _CACHE
    if _CACHE is None:
        _CACHE = load()
    return qhash(q) in _CACHE


def main():
    hs = set()
    # PER-ENTRY FIELDS, not a hardcoded "instruction". The old loop read
    # json.loads(line)["instruction"] for every file, so registering control_sft_text_heldout
    # (field `question`) or humaneval (field `prompt`) would have raised KeyError -- or worse,
    # under a .get() would have hashed nothing and printed a count of 0 beside a green
    # fingerprint. A registry that adds files while the hasher reads one field name is the
    # same silent no-op in a new place.
    uncovered = []
    for name, e in sorted(REGISTRY.items()):
        path = os.path.join(ROOT, e["path"])
        fields = e["question_field"]
        if fields is None:
            # Registered, deliberately not hashed: its leak surface is not a question and the
            # hash unit is undecided. Printed every run so it cannot be forgotten silently.
            uncovered.append(name)
            continue
        if not os.path.exists(path):
            print(f"  missing (skipped): {e['path']}")
            continue
        n, miss = 0, 0
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                if not line.strip():
                    continue
                row = json.loads(line)
                val = next((row[f] for f in fields if f in row), None)
                if val is None:
                    miss += 1
                    continue
                hs.add(qhash(val))
                n += 1
        # A registered file contributing ZERO hashes is the failure this fixes; say so loudly
        # rather than printing a 0 among the counts.
        if n == 0:
            raise RuntimeError(
                f"{name}: registered with question_field {fields} but produced NO hashes "
                f"({miss} rows had none of those fields). Fix the field list or set it to None "
                f"with a why -- a registered file that hashes nothing is the bug this registry "
                f"exists to prevent"
            )
        note = f", {miss} row(s) with no {'/'.join(fields)}" if miss else ""
        print(f"  {os.path.basename(path)}: {n}{note}")
    if uncovered:
        print(f"  NOT HASHED (question_field None, leak surface is not a question): "
              f"{', '.join(uncovered)}")
    # AN EMPTY HASH SET IS THE 2026-08-30 CONTAMINATION ITSELF -- 19 of 20 holdout questions
    # packed into sft_all.pt because the set was empty -- and until now this function would
    # write one and exit 0. MEASURED 2026-09-04 in a fixture tree where every registry path was
    # absent: "0 unique holdout hashes (fp da39a3ee...)" written, rc 0. load() would then accept
    # it, because the fingerprint of zero existing files matches the fingerprint recorded beside
    # zero hashes -- the stale check cannot fire when both sides are consistently empty.
    #
    # So refuse to write. The caller wanted a guard and would have got a file that says
    # "nothing is held out", which is the one answer that must never be produced silently.
    if not hs:
        raise RuntimeError(
            f"refusing to write an EMPTY hash set to {HASH_PATH}: none of the "
            f"{len(REGISTRY)} registry entries produced a hash "
            f"({len(uncovered)} are question_field None by design; the rest are missing from "
            f"this tree). An empty holdout set is indistinguishable from no guard -- it is the "
            f"2026-08-30 sft_all.pt contamination. Run this where the eval data exists."
        )
    os.makedirs(os.path.dirname(HASH_PATH), exist_ok=True)
    with open(HASH_PATH, "w", encoding="utf-8") as f:
        f.write(f"# fp:{_fingerprint()}\n")
        f.write("\n".join(sorted(hs)) + "\n")
    print(f"{len(hs)} unique holdout hashes (fp {_fingerprint()}) -> {HASH_PATH}")


if __name__ == "__main__":
    main()
