#!/usr/bin/env python3
"""The eval holdout, as a hash set every data path must exclude.

`python datagen/holdout.py` regenerates data/eval/holdout_hashes.txt from the eval
files; importers use `is_holdout(question)`.

Fail-closed: the hash file carries a fingerprint of the eval files that produced
it. is_holdout() RAISES if the file is missing, predates fingerprints, or is
stale (an eval file changed since regeneration). A guard that silently returns
False is indistinguishable from no guard at all -- the 2026-08-30 sft_all.pt
contamination (19/20 holdout questions packed because the hash set was empty)
is the reason this is loud, not silent.

# restartable: main() accumulates one hash set and writes HASH_PATH once, which the
# restartability check flags -- correctly, as a shape. It is cheap here and the reason is
# measurable rather than asserted: the whole registry is 13 files and ~31,000 rows of sha1 over
# short strings, a few seconds, and the output is a single derived file that is regenerated by
# re-running the command with no state to resume. A partial write is also impossible to
# mistake for a good one: the file leads with `# fp:<fingerprint>` and load() RAISES on a
# fingerprint mismatch, so an interrupted run leaves a file the next reader refuses rather than
# a short hash set it silently trusts.
"""

import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class UnregisteredEval(KeyError):
    """A name no registry entry covers. Raised rather than returning a path, so an eval
    file cannot be scored before it is registered."""


# THE POPULATION, not a list of four paths. The four-entry EVAL_FILES was correct on its own
# population and its population was the wrong one: data/sft/control_sft_text_heldout.jsonl was
# not in it, so no corpus builder ever excluded it, and 2,114 of 7,523 measurable held-out
# items reached the pretraining corpus with this guard green, fingerprinted and loud
# (facts/contamination.json#cont.heldout_in_pretrain_corpus, e1, 2026-09-04).
#
# COUNTED ON THE POD, because `data/` is gitignored: a laptop glob plus a code grep found 8
# unregistered files and missed 3 that exist only on the pod and are loaded by paths built at
# runtime (gsm8k_zh_holdout, lambada_zh_src, math_hard_eval_v2_1k_fmt). 10, not 8 -- and the
# instrument, not the reasoning, is what differed (de, 2026-09-04).
#
# `question_field` IS A LIST, and may be None. These files disagree on the field name --
# question / instruction / prompt / text / content -- so a registry assuming one name would
# register a file and hash NOTHING from it: a silent no-op under a green check, the same
# failure class as the bug this fixes (e1's point). None is for a file whose leak surface is
# not a question at all, and it REQUIRES a `why` saying what the surface is: without that,
# None becomes the value someone reaches for when they have not looked, and the registry
# records "no question here" where it means "nobody checked".
#
# data/probes/ IS THE OPPOSITE OF A HOLDOUT AND MUST NEVER BE REGISTERED HERE (4c's ruling,
# 2026-09-05). A registry entry tells every corpus builder to EXCLUDE that file's items from
# the pretraining corpus. A probe item file is drawn FROM the corpus on purpose -- readout 2's
# api_cloze.jsonl samples rows the control TRAINED on, and its whole estimator depends on those
# rows having been trained on -- so registering it would exclude real training rows to protect
# an eval that requires them included, which is this registry's purpose inverted. That is why
# the file lives under data/probes/ and not data/eval/: every file under data/eval/ must appear
# here, and check_eval_registry_complete FAILed on the pod for as long as this one sat there.
# A probe whose items must NOT reach the corpus is a holdout and belongs in data/eval/ with an
# entry; the test is which way the contamination runs, not the word "probe".
REGISTRY = {
    "math_test_500": {
        "path": "data/eval/math_test_500.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-08-30",
        "why": "math-500, the metric of record for math; 0.0% contamination on the pod corpus",
    },
    "math_hard_eval_1k": {
        "path": "data/synthetic/math_hard_eval_1k.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-08-30",
        "why": "math-hard v1, retired as a metric (our own generators contaminated it) but still held out",
    },
    "code_holdout_500": {
        "path": "data/eval/code_holdout_500.jsonl",
        "kind": "heldout",
        "question_field": ["instruction"],
        "added": "2026-08-30",
        "why": "code holdout v1",
    },
    "code_holdout_v2_500": {
        "path": "data/eval/code_holdout_v2_500.jsonl",
        "kind": "heldout",
        "question_field": ["instruction"],
        "added": "2026-08-30",
        "why": "code holdout v2",
    },
    "control_sft_text_heldout": {
        "path": "data/sft/control_sft_text_heldout.jsonl",
        "kind": "heldout",
        "question_field": ["question"],
        "added": "2026-09-04",
        "why": "THE FILE THAT WAS MISSING: the control comparison's held-out set, 10,641 rows, "
               "read by eval_heldout.py and six e1_2x scripts. Its absence from the old "
               "four-entry list is why 1,199 held-out rows entered chatml/chat_qa verbatim",
    },
    "humaneval_164": {
        "path": "data/eval/humaneval/humaneval_164.jsonl",
        "kind": "gold",
        "question_field": ["prompt"],
        "added": "2026-09-04",
        "why": "HumanEval, 164 rows, the gold BPB metric's source. build_control_sft_text.py has "
               "an explicit check_no_eval_leak for it, so the SFT path was guarded and no "
               "corpus builder was -- the guarded-in-one-place case",
    },
    "mbpp_sanitized_427": {
        "path": "data/eval/sanitized-mbpp.json",
        "kind": "gold",
        "question_field": ["prompt"],
        "format": "array",
        "added": "2026-09-14",
        "why": "MBPP sanitized, 427 rows (task_id/prompt/code/test_imports/test_list); stage-2 "
               "E0/ET/EC paired MBPP metric source (eval/mbpp_gen.py). Upstream "
               "google-research/google-research mbpp/sanitized-mbpp.json, fetched 2026-09-14",
    },
    "mbpp_holdouts_974": {
        "path": "data/eval/mbpp_holdouts.jsonl",
        "kind": "heldout",
        "question_field": ["text"],
        "added": "2026-09-14",
        "why": "974-row mbpp-train holdout, the MBPP population for "
               "scripts/audit_gate_contamination.py 13-gram audits; distinct id scheme from "
               "sanitized-427, kept as the contamination baseline",
    },
    "phi_l3_stub_holdout_manifest": {
        "path": "data/sft/phi_l3_stub_holdout_manifest.jsonl",
        "kind": "heldout",
        "question_field": ["url"],
        "added": "2026-09-14",
        "why": "273879-row holdout manifest for datagen/build_phi_codeexercises_pack.py; "
               "excluded from the phi SFT pack (owner 3b, registered by 66 to close the registry gap)",
    },
    "gsm8k_zh_holdout": {
        "path": "data/eval/gsm8k_zh_holdout.jsonl",
        "kind": "heldout",
        "question_field": ["instruction"],
        "added": "2026-09-04",
        "why": "7,473 rows, NOT dead: it is the canary of "
               "facts/contamination.json#cont.gsm8k_zh_webhq_scan (status=measured), which names "
               "this exact path in its config.holdout. datagen/prepare_sft.py reads the "
               "non-holdout sibling data/gsm8k_zh.jsonl as an SFT source, so the pair is the "
               "shape that leaks if the exclusion was never wired",
    },
    "math_hard_eval_v2_1k": {
        "path": "data/synthetic/math_hard_eval_v2_1k.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-09-04",
        "why": "math-hard v2, 1,080 rows; read by scan_eval_golds and scan_math_contamination",
    },
    "math_hard_eval_v2_1k_fmt": {
        "path": "data/synthetic/math_hard_eval_v2_1k_fmt.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-09-04",
        "why": "the reformatted copy of v2_1k, same 1,080 questions. Registered separately "
               "because norm() is whitespace-insensitive but not format-insensitive, and a "
               "pod-only file loaded by a runtime path is exactly what the laptop glob missed",
    },
    "math_hard_eval_v2_5k": {
        "path": "data/synthetic/math_hard_eval_v2_5k.jsonl",
        "kind": "eval",
        "question_field": ["instruction"],
        "added": "2026-09-04",
        "why": "math-hard v2 5k, 3,161 rows; read by eval/math_v2_like.py",
    },
    "lambada_en": {
        "path": "data/eval/lambada_en/lambada_test_en.jsonl",
        "kind": "eval",
        "question_field": ["text"],
        "added": "2026-09-04",
        "why": "LAMBADA en, 5,153 rows. `text` is the whole passage including the target word, "
               "so hashing it covers the passage; a corpus copy of the passage IS the leak",
    },
    "lambada_zh": {
        "path": "data/eval/lambada_zh.jsonl",
        "kind": "eval",
        "question_field": None,
        "added": "2026-09-04",
        "why": "NO QUESTION FIELD, and this is measured rather than assumed: the rows carry "
               "context / target / distractor / target_id / src. The leak surface is the "
               "passage plus its target word, not a question, and it may need a different hash "
               "unit than qhash(question) -- context alone would register a field name that "
               "means something different per row. UNCOVERED by the hash set until that unit "
               "is decided; registered so the completeness check sees it and nobody reads its "
               "absence as 'not an eval file'",
    },
    "lambada_zh_src": {
        "path": "data/eval/holdout_v2/lambada_zh_src.jsonl",
        "kind": "eval",
        "question_field": None,
        "added": "2026-09-04",
        "why": "523 rows keyed `content`, the source passages lambada_zh was cut from. Same "
               "undecided hash unit as lambada_zh: `content` is a passage, not a question. "
               "Pod-only, found by counting on the pod rather than globbing the laptop",
    },
}

# Eval names that exist in the codebase's vocabulary but are in no REGISTRY entry and on no
# disk we have. This is a DENYLIST OF NAMES, not a set of registry keys: measured 2026-09-04,
# eval_path("ceval") and eval_path("code_rp1t_handread50") both raise UnregisteredEval, and
# neither contributes an EVAL_FILES path. The comment here previously said they were "kept as
# entries rather than deleted so eval_path still resolves them", which was false in both
# halves -- they are not entries and it does not resolve them. Its only real use is
# _NON_EVAL_PREFIXES-style exclusion in the completeness check, so a scan does not demand a
# registry row for a file nobody has.
KNOWN_ABSENT = {"ceval", "code_rp1t_handread50"}


def _validate_registry(reg=None):
    """Every entry is well formed, and a None question_field carries its reason.

    Called at import: a malformed entry must fail before anything reads the guard, not at the
    first hash. The None check is the load-bearing one -- without it None is the value someone
    reaches for when they have not looked, and the registry records "no question here" where it
    means "nobody checked" (e1's ruling, 2026-09-04).
    """
    reg = REGISTRY if reg is None else reg
    for name, e in sorted(reg.items()):
        for key in ("path", "kind", "question_field", "added", "why"):
            if key not in e:
                raise ValueError(f"registry entry {name!r} is missing {key!r}")
        if e["kind"] not in ("eval", "heldout", "gold"):
            raise ValueError(f"registry entry {name!r} has kind {e['kind']!r}, "
                             "not one of eval/heldout/gold")
        qf = e["question_field"]
        if qf is not None and not (isinstance(qf, list) and qf and all(isinstance(x, str) for x in qf)):
            raise ValueError(f"registry entry {name!r}: question_field must be a non-empty "
                             f"list of field names, or None with a why; got {qf!r}")
        if not str(e.get("why", "")).strip():
            raise ValueError(f"registry entry {name!r} has an empty why")
        if qf is None and len(str(e["why"]).strip()) < 40:
            raise ValueError(
                f"registry entry {name!r} has question_field None and a why too short to say "
                f"what its leak surface IS. None must be a measurement, not a default"
            )


_validate_registry()


def eval_path(name):
    """The absolute path of a registered eval file. Raises on an unregistered name.

    This is the enforcement: a loader that builds its own os.path.join can score a file the
    holdout guard has never heard of, which is how ten eval files sat outside the population.
    """
    e = REGISTRY.get(name)
    if e is None:
        raise UnregisteredEval(
            f"{name!r} is not in datagen/holdout.py REGISTRY. An eval file must be registered "
            f"before it is loaded, or the corpus builders cannot exclude it. Registered: "
            f"{sorted(REGISTRY)}"
        )
    return os.path.join(ROOT, e["path"])


# EVAL_FILES is a DERIVED VIEW, so nothing reads a bare list any more. Kept as a name because
# scripts/harness.py:4231 mirrors it and readers exist; it is now every registry entry that
# contributes hashes, not four hardcoded paths.
EVAL_FILES = [os.path.join(ROOT, e["path"]) for e in REGISTRY.values()]
HASH_PATH = os.path.join(ROOT, "data", "eval", "holdout_hashes.txt")


def norm(q):
    """Whitespace- and punctuation-insensitive key, so a reformatted copy still matches."""
    return "".join(ch for ch in str(q) if not ch.isspace() and ch not in "：:，,。.、（）()")


def qhash(q):
    return hashlib.sha1(norm(q).encode("utf-8")).hexdigest()[:16]


def _fp_inputs():
    """(present, absent) EVAL_FILES paths. The split IS the fingerprint's domain."""
    present = sorted(p for p in EVAL_FILES if os.path.exists(p))
    absent = sorted(p for p in EVAL_FILES if not os.path.exists(p))
    return present, absent


def _fingerprint():
    """sha1 of (basename, file-sha1) for every EXISTING EVAL_FILES entry. Changes
    when an eval file is added, removed, or edited -- which is exactly when the
    hash set must be regenerated.

    SKIPPING ABSENT FILES MAKES THIS MACHINE-DEPENDENT, and that is the whole reason for
    the two guards below. The laptop holds 8 of the 13 registry files and the pod holds
    more, so the two compute DIFFERENT values over the same committed hash set: whichever
    regenerates last leaves the other's load() raising "stale" about a file that never
    changed. Measured 2026-09-04, after de-50 widened the registry from 4 entries to 13 and
    datagen/test_parallel_exact_identity.py died on exactly that.

    Not fixed by hashing the absent NAMES too -- that would make the fp stable across
    machines while still describing a hash set built from fewer files, i.e. a fingerprint
    that verifies and a population that is wrong. The honest split is: only a machine where
    every path resolves may GENERATE (main()), and a machine missing files does not
    recompute at all (load()). 6e's ruling, 2026-09-04."""
    present, _ = _fp_inputs()
    h = hashlib.sha1()
    for path in present:
        h.update(os.path.basename(path).encode())
        h.update(hashlib.sha1(open(path, "rb").read()).digest())
    return h.hexdigest()[:16]


# PER-FILE sha1 OF EVERY REGISTRY FILE, read on the pod 2026-09-04 where all 13 resolve.
# This is what makes the committed fingerprint checkable on a machine holding 5 of them: it
# is not a second source of truth but the SAME inputs _fingerprint() hashes, written down.
# Verified 2026-09-04: feeding these 13 through _fingerprint()'s exact recipe -- basename
# then raw sha1 digest, in sorted-path order -- reproduces the committed 26984613941ab5a2,
# and the 5 files present on a laptop hash to the values recorded here.
#
# WHY NOT WRITE THEM INTO holdout_hashes.txt, which was the obvious place: sft_math.py:218
# and datagen/prepare_sft.py:291 compute `holdout_fp` as sha256 of that file's WHOLE BYTES.
# Adding a manifest line would change every future fp while every pack on disk carries the
# old one, so sft_math.py would refuse to train on packs whose holdout set had not changed.
# The check's own artifact must not invalidate the artifacts it guards.
#
# A file legitimately changes -- a regenerated eval set, a widened registry. Then this dict is
# stale BY CONSTRUCTION and check() reports which entry moved, naming the recorded and the
# observed sha1. Update it from the pod in the same commit that changes the file; a value here
# that nothing produced is worse than no value, so do not hand-edit it to make a check pass.
REGISTRY_SHA1 = {
    "code_holdout_500": "a43dde77332cffe863be26f57d347c9be8198a33",
    "code_holdout_v2_500": "c9fd62cdf5d4d73167c6284e5c99a5d8a9272a2a",
    "control_sft_text_heldout": "b3c97dd749d24f4b9c9eb1e67d8912b5cd5e4ea7",
    "gsm8k_zh_holdout": "8ccbf8b2314f9f7b12874b86af931fe2bba41307",
    "humaneval_164": "ee3a74711c43ea4f4a5d8187364fefd539240499",
    "mbpp_sanitized_427": "8e6b6c0a1d746e060a492df8efcd5ee2270ace13",
    "mbpp_holdouts_974": "c0bb8355ddc670dd61c71a826fddef0532c98a76",
    "phi_l3_stub_holdout_manifest": "fc86175871b6ff6bfbec70859fed48f19241e1b0",
    "lambada_en": "7cf46a68e4e2d89b0fbcf98cef843b00cc8a221c",
    "lambada_zh": "52771e5909a032393447278c51017dba302aef5c",
    "lambada_zh_src": "930bc8d5e6ea9c16be0b1e90ef6bd6dac77da7a3",
    "math_hard_eval_1k": "6ad174ece54ee7927549e489c07a040576598e1d",
    "math_hard_eval_v2_1k": "b971639725b3a745b6502eb805931f33ee2e8e31",
    "math_hard_eval_v2_1k_fmt": "ca7d29489294d341a1dbd643ac4fb507c5bd6054",
    "math_hard_eval_v2_5k": "ecc339d4381de95bd3910200f33279168a974ed6",
    "math_test_500": "dbe2dff2e562dfa9c5ca2bd7b6f619bdf24ab5b9",
}


def _fingerprint_from_recorded(reg=None, sha1s=None):
    """_fingerprint()'s value over ALL registry files, from REGISTRY_SHA1 instead of disk.

    The same recipe as _fingerprint() -- basename, then the raw sha1 digest, in sorted-path
    order -- so a divergence means one of them changed, which is the point. Raises if a
    registry entry has no recorded sha1: a missing input must not silently shrink the domain,
    which is the defect _fingerprint()'s own docstring is about.
    """
    reg = REGISTRY if reg is None else reg
    sha1s = REGISTRY_SHA1 if sha1s is None else sha1s
    missing = sorted(set(reg) - set(sha1s))
    if missing:
        raise RuntimeError(
            f"REGISTRY_SHA1 has no sha1 for {missing} -- a fingerprint over a subset of the "
            f"registry is reproducible on no machine. Read them on the pod and record them.")
    h = hashlib.sha1()
    for path, name in sorted((os.path.join(ROOT, reg[n]["path"]), n) for n in reg):
        h.update(os.path.basename(path).encode())
        h.update(bytes.fromhex(sha1s[name]))
    return h.hexdigest()[:16]


def load():
    if not os.path.exists(HASH_PATH):
        raise RuntimeError(
            f"{HASH_PATH} missing -- the holdout guard is unloaded. "
            "Run `python datagen/holdout.py` to regenerate."
        )
    lines = [l.strip() for l in open(HASH_PATH, encoding="utf-8") if l.strip()]
    fp = next((l[5:] for l in lines if l.startswith("# fp:")), None)
    if fp is None:
        raise RuntimeError(
            f"{HASH_PATH} has no fingerprint (old format) -- the guard may be stale. "
            "Run `python datagen/holdout.py` to regenerate."
        )
    declared = next((int(l[4:]) for l in lines if l.startswith("# n:")), None)
    n_body = sum(1 for l in lines if not l.startswith("#"))
    if declared is None:
        raise RuntimeError(
            f"{HASH_PATH} has no '# n:<count>' header -- a guard whose body size is not "
            "declared can be truncated with nothing noticing. Run `python datagen/holdout.py` "
            "to regenerate.")
    if declared != n_body:
        raise RuntimeError(
            f"{HASH_PATH} header declares {declared} hashes but the body holds {n_body} -- "
            "the file was truncated or hand-edited. A header-only change cannot fix a guard; "
            "run `python datagen/holdout.py` where every registry source resolves.")
    present, absent = _fp_inputs()
    if absent:
        # NOT VERIFIABLE HERE, so do not pretend either way. Recomputing would hash a
        # subset and call the committed fp stale for files this machine simply lacks --
        # a false staleness that reads exactly like a real one, and the fix an operator
        # reaches for (regenerate) replaces a 13-file hash set with an 8-file one.
        # Trusting-and-saying-so keeps the guard loaded and the limit visible.
        print(f"holdout: fp not verifiable here, {len(absent)} of "
              f"{len(present) + len(absent)} files absent -- trusting the committed "
              f"{fp}. Absent: {', '.join(os.path.basename(p) for p in absent[:4])}")
    elif fp != _fingerprint():
        raise RuntimeError(
            f"{HASH_PATH} is stale: eval files changed since it was generated. "
            "Run `python datagen/holdout.py` to regenerate."
        )
    return {l for l in lines if not l.startswith("#")}


_CACHE = None


def is_holdout(q):
    global _CACHE
    if _CACHE is None:
        _CACHE = load()
    return qhash(q) in _CACHE


def _iter_questions(path, fields, fmt):
    """Yield question values from one registry file.

    fmt "jsonl" (default): one JSON object per line. fmt "array": a single JSON
    array of objects (sanitized-mbpp.json is one physical line, so line-wise
    json.loads sees the whole array as one row with no question field).
    """
    if fmt == "array":
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        if not isinstance(data, list):
            raise RuntimeError(
                f"{path}: format=array but top level is {type(data).__name__}, not list")
        rows = data
    else:
        with open(path, encoding="utf-8") as fh:
            rows = [json.loads(line) for line in fh if line.strip()]
    for row in rows:
        yield next((row[f] for f in fields if f in row), None)


def _body_coverage_problems(reg, root, got):
    """Names of PRESENT question-bearing files whose questions are not all in the body set.

    The '# n:<count>' header and the raw-file sha1 prove the body is INTERNALLY CONSISTENT with
    its declared size and that the eval files did not change; neither proves the body contains
    THIS registry's questions. A body can carry the right count and a matching fp over a partial
    or copied population (a HOLDOUT_ALLOW_PARTIAL regen, or a file swapped by hand with its
    neighbours), and length/sha1 stay green while is_holdout() silently passes one file's
    questions -- the 2026-09-14 false-green, one level deeper than the count header. This
    recomputes each present file's question subset (the SAME extractor main() uses) and requires
    it to be contained in the committed body.

    Only files PRESENT under root are examined, so on a data-less CI checkout this proves
    nothing and returns [] (it does not fail); the synthetic-fixture selftest covers the
    failure there, independent of the real eval data.
    """
    problems = []
    for name in sorted(reg):
        e = reg[name]
        fields = e.get("question_field")
        if fields is None:
            continue
        p = os.path.join(root, e["path"])
        if not os.path.isfile(p):
            continue
        expected = {qhash(v) for v in _iter_questions(p, fields, e.get("format", "jsonl"))
                    if v is not None}
        missing = expected - got
        if missing:
            problems.append(f"{name}: {len(missing)}/{len(expected)} of its question hashes are "
                            f"not in {os.path.basename(HASH_PATH)} (count/fp can agree while the "
                            f"population is wrong)")
    return problems


def main():
    hs = set()
    # PER-ENTRY FIELDS, not a hardcoded "instruction". The old loop read
    # json.loads(line)["instruction"] for every file, so registering control_sft_text_heldout
    # (field `question`) or humaneval (field `prompt`) would have raised KeyError -- or worse,
    # under a .get() would have hashed nothing and printed a count of 0 beside a green
    # fingerprint. A registry that adds files while the hasher reads one field name is the
    # same silent no-op in a new place.
    uncovered = []
    for name, e in sorted(REGISTRY.items()):
        path = os.path.join(ROOT, e["path"])
        fields = e["question_field"]
        if fields is None:
            # Registered, deliberately not hashed: its leak surface is not a question and the
            # hash unit is undecided. Printed every run so it cannot be forgotten silently.
            uncovered.append(name)
            continue
        if not os.path.exists(path):
            print(f"  missing (skipped): {e['path']}")
            continue
        n, miss = 0, 0
        for val in _iter_questions(path, fields, e.get("format", "jsonl")):
            if val is None:
                miss += 1
                continue
            hs.add(qhash(val))
            n += 1
        # A registered file contributing ZERO hashes is the failure this fixes; say so loudly
        # rather than printing a 0 among the counts.
        if n == 0:
            raise RuntimeError(
                f"{name}: registered with question_field {fields} but produced NO hashes "
                f"({miss} rows had none of those fields). Fix the field list or set it to None "
                f"with a why -- a registered file that hashes nothing is the bug this registry "
                f"exists to prevent"
            )
        note = f", {miss} row(s) with no {'/'.join(fields)}" if miss else ""
        print(f"  {os.path.basename(path)}: {n}{note}")
    if uncovered:
        print(f"  NOT HASHED (question_field None, leak surface is not a question): "
              f"{', '.join(uncovered)}")
    # AN EMPTY HASH SET IS THE 2026-08-30 CONTAMINATION ITSELF -- 19 of 20 holdout questions
    # packed into sft_all.pt because the set was empty -- and until now this function would
    # write one and exit 0. MEASURED 2026-09-04 in a fixture tree where every registry path was
    # absent: "0 unique holdout hashes (fp da39a3ee...)" written, rc 0. load() would then accept
    # it, because the fingerprint of zero existing files matches the fingerprint recorded beside
    # zero hashes -- the stale check cannot fire when both sides are consistently empty.
    #
    # So refuse to write. The caller wanted a guard and would have got a file that says
    # "nothing is held out", which is the one answer that must never be produced silently.
    if not hs:
        raise RuntimeError(
            f"refusing to write an EMPTY hash set to {HASH_PATH}: none of the "
            f"{len(REGISTRY)} registry entries produced a hash "
            f"({len(uncovered)} are question_field None by design; the rest are missing from "
            f"this tree). An empty holdout set is indistinguishable from no guard -- it is the "
            f"2026-08-30 sft_all.pt contamination. Run this where the eval data exists."
        )
    # AND REFUSE A PARTIAL ONE, for the same reason one level up. An empty set is the loud
    # case; a set built from 5 of 13 files is the quiet one -- it writes a fingerprint that
    # only this machine can reproduce, so the pod's load() then calls it stale about files
    # that never changed, and the operator's fix (regenerate there) overwrites a 13-file set
    # with a partial one in the other direction. The two machines take turns invalidating
    # each other and every round loses questions from the guard.
    #
    # NOT filtering KNOWN_ABSENT here: measured 2026-09-04, neither `ceval` nor
    # `code_rp1t_handread50` is a REGISTRY key, so they contribute no EVAL_FILES path and
    # nothing to filter. The first version of this block filtered them anyway and added
    # len(KNOWN_ABSENT) to the total, which printed "5 of 15" for a 13-entry registry --
    # a guard reporting a population that does not exist.
    _present, _absent = _fp_inputs()
    if _absent and not os.environ.get("HOLDOUT_ALLOW_PARTIAL"):
        raise RuntimeError(
            f"refusing to regenerate {HASH_PATH} from {len(_present)} of "
            f"{len(EVAL_FILES)} registry files: {len(_absent)} are absent here, so the "
            f"fingerprint written would be reproducible on no other machine and every other "
            f"machine's load() would read it as stale. Regenerate where every path resolves "
            f"(the pod). Absent: "
            f"{', '.join(os.path.basename(p) for p in _absent)}. "
            f"HOLDOUT_ALLOW_PARTIAL=1 to override, which produces a guard covering fewer "
            f"questions than the registry claims."
        )
    os.makedirs(os.path.dirname(HASH_PATH), exist_ok=True)
    body = sorted(hs)
    with open(HASH_PATH, "w", encoding="utf-8") as f:
        f.write(f"# fp:{_fingerprint()}\n")
        f.write(f"# n:{len(body)}\n")
        f.write("\n".join(body) + "\n")
    print(f"{len(body)} unique holdout hashes (fp {_fingerprint()}) -> {HASH_PATH}")


def _selftest_coverage():
    """Assertion D on a SYNTHETIC temp tree, so it fails even on a data-less CI checkout.

    The real-data half of D (check on the pod) proves nothing when no registry file resolves,
    and a guard whose broken world can only be built where the 16 eval files live is untested in
    CI -- exactly the slot the 2026-09-14 false-green slipped through. This world writes tiny
    jsonl/array question files into a temp dir and checks the predicate directly:
      covered body -> []; one file's questions dropped -> that file is named; an absent file and
      a question_field-None entry are both skipped (D speaks only to present question files).
    No global REGISTRY/ROOT/HASH_PATH is mutated, so nothing here can corrupt the committed guard.
    """
    import tempfile

    reg = {
        "x_jsonl": {"path": "data/eval/x.jsonl", "question_field": ["prompt"]},
        "x_array": {"path": "data/eval/y.json", "question_field": ["prompt"], "format": "array"},
        "x_absent": {"path": "data/eval/missing.jsonl", "question_field": ["prompt"]},
        "x_none": {"path": "data/eval/nonq.jsonl", "question_field": None},
    }
    with tempfile.TemporaryDirectory() as d:
        os.makedirs(os.path.join(d, "data/eval"))
        with open(os.path.join(d, "data/eval/x.jsonl"), "w", encoding="utf-8") as f:
            f.write(json.dumps({"prompt": "alpha question"}) + "\n")
            f.write(json.dumps({"prompt": "beta question"}) + "\n")
        with open(os.path.join(d, "data/eval/y.json"), "w", encoding="utf-8") as f:
            json.dump([{"prompt": "gamma array q"}, {"prompt": "delta array q"}], f)
        with open(os.path.join(d, "data/eval/nonq.jsonl"), "w", encoding="utf-8") as f:
            f.write(json.dumps({"url": "not-a-question"}) + "\n")

        def qset(*prompts):
            return {qhash(p) for p in prompts}

        # 1. Fully covered (jsonl + array both present) -> no problem.
        full = qset("alpha question", "beta question", "gamma array q", "delta array q")
        assert _body_coverage_problems(reg, d, full) == [], "full coverage reported a problem"
        # 2. The ARRAY file's questions dropped, count can still match elsewhere -> it is named.
        #    This is the exact shape: right-length body, wrong population.
        no_array = qset("alpha question", "beta question")
        p2 = _body_coverage_problems(reg, d, no_array)
        assert any(s.startswith("x_array:") for s in p2), f"missing array file not named: {p2}"
        assert not any(s.startswith("x_jsonl:") for s in p2), f"covered file flagged: {p2}"
        # 3. The absent file and the question_field-None file are never flagged.
        assert not any("x_absent" in s or "x_none" in s for s in p2), p2
        # 4. Empty body flags every present question file, not just one.
        p4 = _body_coverage_problems(reg, d, set())
        assert {s.split(":", 1)[0] for s in p4} == {"x_jsonl", "x_array"}, p4
    return 4


def _selftest():
    """The two machine-dependence guards, on a REAL registry file made absent.

    The property: a fingerprint computed over a subset is reproducible on no other machine, so
    generation must refuse where a path is missing and load() must not recompute there. Both
    halves matter and they fail in opposite directions -- a missing generation guard writes a
    partial set that invalidates the pod's, a missing load guard raises "stale" about a file
    that never changed. datagen/test_parallel_exact_identity.py died on the second one.

    Mutates by MOVING one real file aside, not by pointing the registry at a fake path: the
    thing under test is what os.path.exists reports for the paths the registry actually
    names, and a fixture path shares the author's assumption about which paths those are.

    IT WRITES TO THE REAL HASH_PATH AND MUST PUT IT BACK BYTE-FOR-BYTE. Measured 2026-09-04:
    a mutation harness that symlinked data/ into a fixture tree had its `main()` write a
    501-line partial set straight through to the committed file, restored from HEAD. So the
    saved bytes are compared after restoring, not assumed, and a mismatch raises rather than
    printing OK -- a selftest that corrupts the artifact it guards is worse than none."""
    import shutil

    # D runs FIRST and unconditionally: it needs no real eval data (synthetic temp tree), so it
    # is the only half of the content-coverage guard that can be exercised on a data-less CI
    # runner. It must not be behind the `if not present: return SKIP` gate below.
    n_cover = _selftest_coverage()

    present, absent = _fp_inputs()
    if not present:
        print(f"holdout selftest: content-coverage assertion D passed on {n_cover} synthetic "
              "world(s); machine-dependence worlds SKIP (no registry file resolves here)")
        return 0
    victim = present[0]
    stash = victim + ".selftest_hidden"
    fp_all = _fingerprint()
    # Saved BEFORE the first thing that can write it: main() below writes HASH_PATH when the
    # refusal is absent, which is exactly the case being tested.
    _hash_saved = (open(HASH_PATH, encoding="utf-8").read()
                   if os.path.exists(HASH_PATH) else None)
    shutil.move(victim, stash)
    try:
        # 1. The fingerprint MOVED, which is the machine-dependence itself.
        fp_minus = _fingerprint()
        assert fp_minus != fp_all, (
            f"hiding {os.path.basename(victim)} did not change the fingerprint "
            f"({fp_all}) -- then it is not computed over the files it claims")
        # 2. Regeneration refuses rather than writing that fingerprint.
        os.environ.pop("HOLDOUT_ALLOW_PARTIAL", None)
        try:
            main()
        except RuntimeError as e:
            assert "refusing to regenerate" in str(e), f"wrong refusal: {str(e)[:120]}"
            assert os.path.basename(victim) in str(e), (
                f"the refusal must NAME the absent file, or an operator cannot act on it: "
                f"{str(e)[:160]}")
        else:
            raise AssertionError(
                f"main() wrote a hash set with {os.path.basename(victim)} absent -- that "
                f"fingerprint is reproducible on no other machine")
        # 3. load() does NOT recompute where files are absent: it must return the committed
        #    set, not raise "stale". This is the half that broke a passing test.
        #
        # ASSERTED AGAINST A HASH SET THIS MACHINE CANNOT REPRODUCE, because the committed
        # one on the tree that hosts this selftest may already match by accident, and then
        # `load() worked` says nothing. MEASURED 2026-09-04: with the `if absent:` branch
        # mutated to `if False:` the earlier version of this assertion stayed GREEN for
        # exactly that reason. So write a file whose fp is a value no computation here can
        # produce -- if load() recomputes, it must raise.
        if _hash_saved is not None:
            with open(HASH_PATH, "w", encoding="utf-8") as f:
                f.write("# fp:" + "f" * 16 + "\n# n:1\n0000000000000000\n")
            hs = load()
            assert hs == {"0000000000000000"}, (
                f"load() returned {hs} rather than the committed set -- it recomputed "
                f"the fingerprint on a machine missing {len(absent) + 1} files, which "
                f"is the false-stale failure")
    finally:
        shutil.move(stash, victim)
        if _hash_saved is not None:
            with open(HASH_PATH, "w", encoding="utf-8") as f:
                f.write(_hash_saved)
            back = open(HASH_PATH, encoding="utf-8").read()
            if back != _hash_saved:
                raise AssertionError(
                    f"the selftest did not restore {HASH_PATH}: {len(back)} bytes back "
                    f"against {len(_hash_saved)} saved. Restore it from git before trusting "
                    f"the holdout guard.")
    assert _fingerprint() == fp_all, "the selftest did not restore the file it hid"
    n_chk = _selftest_check()
    print(f"holdout selftest OK: content-coverage D on {n_cover} synthetic world(s); hiding "
          f"{os.path.basename(victim)} moves the fp ({fp_all} -> {fp_minus}), regeneration "
          f"refuses and names it, load() still loads; --check correct on {n_chk} worlds")
    return 0


def _selftest_check():
    """check()'s two added assertions, on worlds that break each one.

    THE POINT OF WORLD 1 is 6e's stated broken world: a registry ENTRY REMOVED. The committed
    hash set then describes a file list the registry no longer names, and every consumer reads
    a guard covering questions nobody declared. Nothing on a partial machine could see this
    before -- load() trusts the committed fp there by design, and that is correct; what was
    missing is a second reader that does not need the files.

    Worlds are built by mutating the REGISTRY dict and REGISTRY_SHA1, not by touching
    data/eval/holdout_hashes.txt: the artifact is what 29,923 hashes of real guard live in, and
    a selftest that rewrites it can corrupt the thing it verifies. That already happened once
    here -- the docstring above records a 501-line partial set written straight through to the
    committed file -- so this one never opens it for writing.
    """
    global REGISTRY, REGISTRY_SHA1

    saved_reg, saved_sha = dict(REGISTRY), dict(REGISTRY_SHA1)
    n = 0
    try:
        # 0. The real tree passes, or the three worlds below prove only that check() can fail.
        check()
        n += 1

        # 1. A REGISTRY ENTRY REMOVED -> the derived fp moves and check() must FAIL. 6e's world.
        victim = sorted(REGISTRY)[0]
        REGISTRY = {k: v for k, v in saved_reg.items() if k != victim}
        REGISTRY_SHA1 = {k: v for k, v in saved_sha.items() if k != victim}
        try:
            check()
            raise AssertionError(
                f"removing registry entry {victim!r} left --check GREEN: the committed "
                f"fingerprint is then a number nothing reads, and the guard can cover a file "
                f"list the registry does not declare")
        except RuntimeError as e:
            assert "declares fingerprint to" in str(e), f"wrong refusal: {str(e)[:160]}"
            # It must say BOTH numbers, or an operator cannot tell which side moved.
            assert saved_sha and "carries fp" in str(e), f"refusal names one side only: {str(e)[:160]}"
        n += 1
        REGISTRY, REGISTRY_SHA1 = dict(saved_reg), dict(saved_sha)

        # 2. A PRESENT FILE'S CONTENT CHANGED -> C must FAIL, naming the file.
        #
        #    MUTATING THE FILE, not the recorded sha1, and that is the whole difficulty. Flipping
        #    REGISTRY_SHA1[local] moves the DERIVED fp too, so B fires first and C is never
        #    reached -- my first version asserted `local in msg or "declares fingerprint" in msg`
        #    and was GREEN with the entire sha1 comparison deleted (`if False:`). An `or` across
        #    two assertions means neither is tested.
        #
        #    So: append a byte to the real file, and repair REGISTRY_SHA1 to the file's NEW hash
        #    so B still passes. Then the only thing that can fail is C -- against the committed
        #    fp, which no longer matches either, so the fp line is repaired in the same way. The
        #    file is restored byte-for-byte in the finally, and the restore is VERIFIED, because
        #    this selftest writes to a real registry file.
        local = next((nm for nm in sorted(saved_reg)
                      if os.path.isfile(os.path.join(ROOT, saved_reg[nm]["path"]))), None)
        if local is None:
            print("  (world 2 skipped: no registry file resolves here to mutate)")
        else:
            lp = os.path.join(ROOT, saved_reg[local]["path"])
            original = open(lp, "rb").read()
            try:
                with open(lp, "wb") as fh:
                    fh.write(original + b'{"instruction": "a row this file did not have"}\n')
                new_sha = hashlib.sha1(open(lp, "rb").read()).hexdigest()
                assert new_sha != saved_sha[local], "appending a row did not change the sha1"
                # B repaired: REGISTRY_SHA1 now agrees with the file on disk, so the derived fp
                # is stable -- but it is NOT the committed one, so B would fire on that instead.
                # Point C at the file while asking B's comparison to see agreement: recorded
                # equals disk, and the committed fp is compared against the ORIGINAL recording.
                REGISTRY_SHA1 = dict(saved_sha)
                try:
                    check()
                    raise AssertionError(
                        f"{local}'s file changed on disk and --check stayed GREEN: the committed "
                        f"hash set need not describe the files on this machine")
                except RuntimeError as e:
                    msg = str(e)
                    assert "hashes" in msg and local in msg, (
                        f"the refusal must be C (a file differs from its recorded sha1) and must "
                        f"NAME the file; got: {msg[:200]}")
                    assert "declares fingerprint to" not in msg, (
                        f"B fired instead of C, so C is still untested: {msg[:200]}")
                n += 1
            finally:
                with open(lp, "wb") as fh:
                    fh.write(original)
                back = open(lp, "rb").read()
                if back != original:
                    raise AssertionError(
                        f"the selftest did not restore {lp}: {len(back)} bytes against "
                        f"{len(original)} saved. Restore it from git before trusting the guard.")
                REGISTRY_SHA1 = dict(saved_sha)

        # 2b. AN ABSENT FILE MUST NOT BE COUNTED AS CHECKED. Found by mutation: adding absent
        #     files to `checked` left every other assertion green, and the printed line then
        #     claims 13 files hash as recorded on a machine holding 5. A count that overstates
        #     verification is the same defect class as a check that verifies nothing.
        import contextlib
        import io

        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            check()
        out = buf.getvalue()
        n_present = sum(1 for nm in saved_reg
                        if os.path.isfile(os.path.join(ROOT, saved_reg[nm]["path"])))
        assert f"{n_present} file(s) hash as recorded" in out, (
            f"--check does not report exactly the {n_present} file(s) present here as hashed; "
            f"an absent file counted as checked reads as verification that did not happen. "
            f"Printed: {out[:300]!r}")
        if n_present < len(saved_reg):
            assert "NOT CHECKABLE HERE" in out, (
                "files are absent and --check did not name them as not checkable")
        n += 1

        # 3. A REGISTRY ENTRY WITH NO RECORDED sha1 -> raise rather than fingerprint a subset.
        #    The failure _fingerprint()'s own docstring is about, one level up: a fingerprint
        #    over fewer files than the registry names is reproducible on no machine, and a
        #    silent skip is what makes it look reproducible.
        REGISTRY_SHA1 = {k: v for k, v in saved_sha.items() if k != sorted(saved_sha)[-1]}
        try:
            _fingerprint_from_recorded()
            raise AssertionError(
                "a registry entry with no recorded sha1 was silently skipped -- the derived "
                "fingerprint then covers a subset while claiming to cover the registry")
        except RuntimeError as e:
            assert "no sha1 for" in str(e), f"wrong refusal: {str(e)[:160]}"
        n += 1
        # RESTORED BEFORE WORLD 4, and this line is load-bearing. Without it world 4 inherits a
        # REGISTRY_SHA1 missing an entry, so `if not got:` -> `if False:` went RED on world 3's
        # "no sha1 for [...]" refusal instead of on the empty-set assertion -- red, and for the
        # wrong reason, which is indistinguishable from tested. Found by mutation.
        REGISTRY_SHA1 = dict(saved_sha)

        # 4. AN EMPTY HASH SET MUST REFUSE. This is de's own assertion in check(), not mine, and
        #    mutation found nothing tested it: `if not got:` -> `if False:` left every world
        #    above GREEN. It is also the assertion that matters most -- an empty set means
        #    is_holdout() returns False for every question, which IS the 2026-08-30
        #    contamination (19 of 20 holdout questions packed into sft_all.pt).
        #
        #    load() is monkeypatched rather than writing an empty HASH_PATH: the committed file
        #    holds 29,923 real hashes and this selftest has already corrupted it once in its
        #    history (see _selftest above). The subject here is check()'s reaction to an empty
        #    return, so the empty return is what is faked. Patched through this module's own
        #    globals(), not `import datagen.holdout`: --selftest runs this file as a SCRIPT, so
        #    that import fails with ModuleNotFoundError (measured), and check() resolves `load`
        #    from these globals either way.
        g = globals()
        saved_load = g["load"]
        try:
            g["load"] = lambda: set()
            try:
                check()
                raise AssertionError(
                    "check() accepted an EMPTY hash set: is_holdout() then returns False for "
                    "every question and nothing is excluded, which is the 2026-08-30 "
                    "sft_all.pt contamination this guard exists to prevent")
            except RuntimeError as e:
                assert "zero hashes" in str(e), f"wrong refusal: {str(e)[:160]}"
            n += 1
        finally:
            g["load"] = saved_load

        # 5. FORMAT DISPATCH: a single-line JSON ARRAY source (sanitized-mbpp.json is one
        #    physical line) must yield every object's question via format="array", while
        #    jsonl yields one per line. The defect this fixes (2026-09-14): line-wise
        #    json.loads read the whole 427-row array as one row with no prompt key and the
        #    regenerate died on "1 rows had none", so the new sources contributed zero hashes
        #    while the hand-bumped fp header read green.
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            arr = os.path.join(td, "arr.json")
            with open(arr, "w", encoding="utf-8") as fh:
                json.dump([{"prompt": "p0"}, {"prompt": "p1"}, {"x": 0}], fh)
            assert list(_iter_questions(arr, ["prompt"], "array")) == ["p0", "p1", None]
            jl = os.path.join(td, "rows.jsonl")
            with open(jl, "w", encoding="utf-8") as fh:
                fh.write('{"text": "t0"}\n{"text": "t1"}\n')
            assert list(_iter_questions(jl, ["text"], "jsonl")) == ["t0", "t1"]
            notlist = os.path.join(td, "obj.json")
            with open(notlist, "w", encoding="utf-8") as fh:
                json.dump({"prompt": "p"}, fh)
            try:
                list(_iter_questions(notlist, ["prompt"], "array"))
                raise AssertionError(
                    "format=array on a non-list top level must raise, not hash zero rows")
            except RuntimeError as e:
                assert "not list" in str(e), f"wrong refusal: {str(e)[:120]}"
        n += 1

        # 6. HEADER/BODY MISMATCH MUST FAIL load(), regardless of fp verifiability. This is the
        #    false-green 2026-09-14: a hand-edited fp header over an UNCHANGED 29,923-line body
        #    passed check() while the three newly registered sources contributed nothing. The
        #    test runs against a temp HASH_PATH with _fp_inputs faked to "all absent" so the fp
        #    is trusted by design and the count assertion is the only thing that can fire.
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            tmp_hash = os.path.join(td, "holdout_hashes.txt")
            with open(tmp_hash, "w", encoding="utf-8") as fh:
                fh.write("# fp:" + "f" * 16 + "\n# n:2\n0000000000000000\n")
            gg = globals()
            sv_hash, sv_inputs = gg["HASH_PATH"], gg["_fp_inputs"]
            gg["HASH_PATH"] = tmp_hash
            gg["_fp_inputs"] = lambda: ([], ["fake-absent"])
            try:
                load()
                raise AssertionError(
                    "load() accepted a guard whose # n: header disagrees with its body -- a "
                    "hand-bumped header over a stale body would again read green")
            except RuntimeError as e:
                assert "declares 2" in str(e) and "holds 1" in str(e), str(e)[:160]
            finally:
                gg["HASH_PATH"], gg["_fp_inputs"] = sv_hash, sv_inputs
        n += 1
    finally:
        REGISTRY, REGISTRY_SHA1 = saved_reg, saved_sha
    return n


def check():
    """Assert the committed guard LOADS, without regenerating it. What CI actually wants.

    CI ran `python datagen/holdout.py`, which is the REGENERATE path, on a runner that holds 5 of
    the 13 registry files. d2c95b1c gave that path a correct refusal -- a fingerprint computed from
    a partial set is reproducible on no other machine -- and CI went red on it, which is the
    refusal working and the caller asking the wrong question. Nothing in CI needs the file rebuilt:
    a runner cannot produce a valid one, and the committed file is what every consumer reads.

    What CI can honestly assert is that the committed guard loads and covers something, which is
    the failure that would actually hurt -- a missing or truncated holdout_hashes.txt means
    is_holdout() raises or silently passes contaminated questions. load() already handles the
    partial machine: it trusts the committed fp and prints how many files it could not verify,
    rather than recomputing a false staleness.

    Regenerating stays a deliberate act on the pod, where every path resolves.

    TWO ASSERTIONS ADDED 2026-09-04 (6e's spec), because "it loads and is non-empty" passes on
    a guard built from the wrong files:

      B. THE COMMITTED FINGERPRINT MATCHES THE REGISTRY'S DECLARED FILE LIST. Recomputing from
         disk cannot say this on a partial machine -- that is why load() trusts the committed
         value -- so it is recomputed from REGISTRY_SHA1, which covers all 13 wherever this
         runs. A registry entry removed changes the derived value and this FAILs, which is the
         broken world 6e named. Without it, the committed fp is a number no CI run reads.
      C. EVERY FILE PRESENT HERE HASHES AS RECORDED, and absent ones are reported by name as
         "not checkable here" rather than counted as verified. On CI that is 5 of 13; on the
         pod it is all 13, so the same command gets stronger where the data is without a flag.

    Neither regenerates anything. HOLDOUT_ALLOW_PARTIAL is not read here and must stay out of
    CI: it exists to write a knowingly partial guard, which is the opposite of verifying one.
    """
    got = load()
    if not got:
        raise RuntimeError(
            f"{HASH_PATH} loaded but holds zero hashes -- the holdout guard is empty, so "
            f"is_holdout() returns False for every question and nothing is excluded. Regenerate "
            f"on the pod with `python datagen/holdout.py`.")
    present, absent = _fp_inputs()

    # B. The committed fp against the registry's declared list, machine-independently.
    committed = next((l.strip()[5:] for l in open(HASH_PATH, encoding="utf-8")
                      if l.startswith("# fp:")), None)
    derived = _fingerprint_from_recorded()
    if committed != derived:
        raise RuntimeError(
            f"{HASH_PATH} carries fp {committed}, but the {len(REGISTRY)} files REGISTRY "
            f"declares fingerprint to {derived}. The committed hash set was built from a "
            f"different file list than the registry now names -- an entry was added, removed, "
            f"or its file changed. Regenerate on the pod, and if a file legitimately changed, "
            f"update REGISTRY_SHA1 from the pod in the same commit.")

    # C. Files present here must hash as recorded. Absent ones are named, never counted.
    wrong, checked = [], []
    for name in sorted(REGISTRY):
        p = os.path.join(ROOT, REGISTRY[name]["path"])
        if not os.path.isfile(p):
            continue
        got_sha = hashlib.sha1(open(p, "rb").read()).hexdigest()
        if got_sha != REGISTRY_SHA1[name]:
            wrong.append(f"{name}: {os.path.basename(p)} hashes {got_sha[:12]}, recorded "
                         f"{REGISTRY_SHA1[name][:12]}")
        else:
            checked.append(name)
    if wrong:
        raise RuntimeError(
            f"{len(wrong)} registry file(s) differ from the recorded sha1, so the committed "
            f"hash set does not describe the files on this machine:\n  " + "\n  ".join(wrong)
            + "\nIf the change is intended, regenerate on the pod and update REGISTRY_SHA1 in "
              "the same commit. If it is not, this machine's copy is corrupt or stale.")

    # D. CONTENT COVERAGE, beyond the count header. Every PRESENT question-bearing file's
    # question hashes must actually be in the body -- a count-consistent, sha1-consistent body
    # over a wrong/partial population must FAIL. Absent files are not examined here (CI has no
    # data); the synthetic-fixture selftest world proves D fires regardless.
    coverage = _body_coverage_problems(REGISTRY, ROOT, got)
    if coverage:
        raise RuntimeError(
            f"{HASH_PATH} is count/fp-consistent but does not cover the registry's questions on "
            f"{len(coverage)} file(s) present here:\n  " + "\n  ".join(coverage[:6])
            + "\nThis is a header-only or partial body: the right count over the wrong "
              "population. Regenerate on the pod with `python datagen/holdout.py`.")

    print(f"holdout guard loads: {len(got)} hashes, {len(present)} of {len(EVAL_FILES)} registry "
          f"files present here"
          + (f" ({len(absent)} absent, fp not verifiable from disk)" if absent else
             ", fp verified from disk"))
    print(f"  fp {committed} matches the registry's {len(REGISTRY)} declared files "
          f"(derived from REGISTRY_SHA1)")
    print(f"  {len(checked)} file(s) hash as recorded: {', '.join(checked)}")
    if absent:
        print(f"  {len(absent)} NOT CHECKABLE HERE: "
              f"{', '.join(os.path.basename(p) for p in absent)}")
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(_selftest())
    elif "--check" in sys.argv:
        sys.exit(check())
    sys.exit(main() or 0)
