#!/usr/bin/env python3
# restartable: a 400-document read with one write at the end; an interrupt costs the
# ~2 min re-read and nothing else, and the draw is seeded (Random(23)) so a re-run
# reproduces the same sample rather than a different one -- resuming would be more
# machinery than repeating.
"""Base rate of generated markup in code_rp1t: 400 docs uniform for the RATE, plus a
length-weighted token fraction with its own basis.

The 26-of-40 figure that motivated this came from NEAR-DUP PAIRS, which is a biased view by
construction: generated files are near-duplicates of each other, so they are over-represented
among pairs at any threshold. This draws from the domain instead. Two numbers, because they
answer different questions and a filter is budgeted in tokens, not documents:
  rate_docs   -- fraction of documents that are markup (uniform draw, binomial CI)
  frac_tokens -- fraction of TOKENS in markup docs, estimated over the same draw with each
                 doc weighted by its own token count; generated HTML is long, so this is the
                 number a filter's yield is read against and it is NOT the doc rate.
Classification is by extension where the row carries one, else by content sniff -- both are
recorded per doc so a human can audit the rule rather than trust it.
"""
import glob, json, os, random, re
from tokenizers import Tokenizer

ROOT = "/work/aupai"
TOK = Tokenizer.from_file(f"{ROOT}/data/tokenizer.json")
N = 400
MARKUP_EXT = {".html", ".htm", ".xhtml", ".xml", ".svg", ".rss", ".atom", ".wsdl", ".xsd", ".plist"}
DOC_HINT = re.compile(r"Generated by javadoc|<!DOCTYPE|<\?xml|NewPage|Generated by (?:Doxygen|Sphinx)", re.I)

def classify(text, path):
    ext = os.path.splitext(str(path or ""))[1].lower()
    if ext in MARKUP_EXT:
        return "markup", f"ext{ext}"
    head = text[:600]
    if DOC_HINT.search(head):
        return "markup", "sniff:doctype-or-generator"
    tags = len(re.findall(r"<[a-zA-Z/!?][^>]{0,80}>", text[:4000]))
    if tags >= 20:
        return "markup", f"sniff:{tags}tags-in-4k"
    return "code", f"ext{ext or '-'}"

def main():
    shards = sorted(glob.glob(f"{ROOT}/data/corpus/code_rp1t/*.jsonl"))
    rng = random.Random(23)
    # uniform over DOCUMENTS requires knowing line counts; count lines once per sampled shard
    picks = {}
    for _ in range(N * 3):  # oversample shard slots, dedup below
        picks.setdefault(rng.choice(shards), []).append(rng.random())
    rows, seen = [], 0
    for shard, slots in picks.items():
        with open(shard, encoding="utf-8") as f:
            lines = f.readlines()
        if not lines:
            continue
        for u in slots:
            if len(rows) >= N:
                break
            ln = int(u * len(lines))
            try:
                d = json.loads(lines[ln])
            except Exception:
                continue
            t = d.get("content") or d.get("text") or ""
            if not t:
                continue
            kind, why = classify(t, d.get("path") or d.get("file") or "")
            rows.append({"kind": kind, "why": why, "tokens": len(TOK.encode(t).ids),
                         "chars": len(t), "shard": os.path.basename(shard), "line": ln,
                         "head": t[:160]})
            seen += 1
        if len(rows) >= N:
            break
    n = len(rows)
    m = sum(1 for r in rows if r["kind"] == "markup")
    tok_all = sum(r["tokens"] for r in rows)
    tok_m = sum(r["tokens"] for r in rows if r["kind"] == "markup")
    p = m / n
    se = (p * (1 - p) / n) ** 0.5
    out = {
        "n_docs": n,
        "rate_docs": round(p, 4),
        "rate_docs_ci95": [round(max(0, p - 1.96 * se), 4), round(min(1, p + 1.96 * se), 4)],
        "frac_tokens": round(tok_m / tok_all, 4) if tok_all else None,
        "frac_tokens_basis": ("token-weighted over the SAME 400-doc uniform draw; this is a "
                              "ratio estimator, so its error is larger than the doc rate's "
                              "binomial CI and no CI is given for it"),
        "mean_tokens_markup": round(tok_m / max(1, m)),
        "mean_tokens_code": round((tok_all - tok_m) / max(1, n - m)),
        "why_counts": {},
    }
    for r in rows:
        out["why_counts"][r["why"]] = out["why_counts"].get(r["why"], 0) + 1
    json.dump({"summary": out, "sample": rows}, open(f"{ROOT}/runs/code_rp1t_markup_rate.json", "w"),
              ensure_ascii=False, indent=1)
    print(json.dumps(out))

if __name__ == "__main__":
    main()
