#!/usr/bin/env python3
"""Experiment log: one JSONL row per GPU run, rendered to EXPERIMENTS.md.

Every GPU run gets a record BEFORE it starts and a result appended when it ends:

  python scripts/exp.py start --name sft_v3 --cmd "torchrun ..." --notes "350K short mix"
  python scripts/exp.py done  --name sft_v3 --result "math-500 34.2%" --status ok

Rows live in runs/experiments.jsonl; `python scripts/exp.py render` rewrites
EXPERIMENTS.md (newest first) so the table is reviewable in the repo.
"""

import argparse
import json
import os
import subprocess
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG = os.path.join(ROOT, "runs", "experiments.jsonl")
MD = os.path.join(ROOT, "EXPERIMENTS.md")


def rows():
    if not os.path.exists(LOG):
        return []
    return [json.loads(l) for l in open(LOG, encoding="utf-8") if l.strip()]


def write(rs):
    os.makedirs(os.path.dirname(LOG), exist_ok=True)
    with open(LOG, "w", encoding="utf-8") as f:
        for r in rs:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def now():
    return time.strftime("%Y-%m-%d %H:%M")


def git_commit():
    try:
        return subprocess.check_output(
            ["git", "-C", ROOT, "rev-parse", "--short", "HEAD"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""  # pod checkout is not a git repo; filled in when the log is synced back


def render():
    rs = sorted(rows(), key=lambda r: r.get("started", ""), reverse=True)
    n_ok = sum(1 for r in rs if r.get("status") == "ok")
    lines = [
        "# Experiments",
        "",
        "Auto-generated by `scripts/exp.py` — every GPU run is recorded here.",
        "",
        f"{len(rs)} runs, {n_ok} completed. Newest first.",
        "",
        "| started | name | status | result | notes | commit |",
        "|---|---|---|---|---|---|",
    ]
    for r in rs:
        cells = [r.get(k, "") or "" for k in ("started", "name", "status", "result", "notes", "commit")]
        lines.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ") for c in cells) + " |")
    lines += ["", "## What each run taught us", ""]
    for r in rs:
        if not (r.get("hypothesis") or r.get("finding") or r.get("decision")):
            continue
        lines.append(f"### {r.get('name')} — {r.get('result') or r.get('status')}")
        if r.get("hypothesis"):
            lines.append(f"- **Asked:** {r['hypothesis']}")
        if r.get("finding"):
            lines.append(f"- **Learned:** {r['finding']}")
        if r.get("decision"):
            lines.append(f"- **So:** {r['decision']}")
        lines.append("")
    lines += ["<details><summary>Commands</summary>", ""]
    for r in rs:
        lines.append(f"- **{r.get('name')}** (`{r.get('started')}`): `{r.get('cmd', '')}`")
    lines += ["", "</details>", ""]
    open(MD, "w", encoding="utf-8").write("\n".join(lines))
    return MD


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="action", required=True)
    s = sub.add_parser("start")
    s.add_argument("--name", required=True)
    s.add_argument("--cmd", default="")
    s.add_argument("--notes", default="")
    s.add_argument(
        "--hypothesis", default="", help="what this run is meant to test, written BEFORE it starts"
    )
    d = sub.add_parser("done")
    d.add_argument("--name", required=True)
    d.add_argument("--result", default="")
    d.add_argument("--status", default="ok")
    d.add_argument("--finding", default="", help="what the number means — the interpretation, not the number")
    d.add_argument("--decision", default="", help="what changes next because of this result")
    m = sub.add_parser("merge", help="merge another experiments.jsonl into this one (pod sync)")
    m.add_argument("--from", dest="src", required=True)
    sub.add_parser("render")
    sub.add_parser("list")
    a = ap.parse_args()

    if a.action == "start":
        rs = rows()
        rs.append(
            {
                "started": now(),
                "name": a.name,
                "status": "running",
                "cmd": a.cmd,
                "notes": a.notes,
                "hypothesis": a.hypothesis,
                "result": "",
                "finding": "",
                "decision": "",
                "ended": "",
                "commit": git_commit(),
            }
        )
        write(rs)
        print(f"logged start: {a.name}")
    elif a.action == "done":
        rs = rows()
        for r in reversed(rs):
            if r["name"] == a.name and r["status"] == "running":
                r.update(
                    status=a.status, result=a.result, finding=a.finding, decision=a.decision, ended=now()
                )
                break
        else:
            rs.append(
                {
                    "started": now(),
                    "name": a.name,
                    "status": a.status,
                    "cmd": "",
                    "notes": "",
                    "hypothesis": "",
                    "result": a.result,
                    "finding": a.finding,
                    "decision": a.decision,
                    "ended": now(),
                    "commit": git_commit(),
                }
            )
        write(rs)
        print(f"logged done: {a.name} -> {a.result}")
    elif a.action == "merge":
        incoming = [json.loads(l) for l in open(a.src, encoding="utf-8") if l.strip()]
        out, idx = [], {}
        for r in sorted(rows() + incoming, key=lambda r: r.get("started", "")):
            k = (r["name"], r["started"])
            if k in idx:
                for f in ("result", "finding", "decision", "hypothesis", "commit", "ended", "cmd", "notes"):
                    if r.get(f) and not out[idx[k]].get(f):
                        out[idx[k]][f] = r[f]
            else:
                idx[k] = len(out)
                out.append(r)
        write(out)
        print(f"merged {len(incoming)} incoming rows -> {len(out)} total")
    elif a.action == "list":
        for r in rows():
            print(f"{r['started']}  {r['name']:<20} {r['status']:<8} {r.get('result', '')}")
    print(render())


if __name__ == "__main__":
    main()
