#!/usr/bin/env python3
"""Generate and verify data/ledger_transport_schema.json — the transport verb's contract.

WHY A FILE. `pod_pull_ledgers.py` takes row identity from `ledger_audit.KEYS`, which is a
dict of Python lambdas. After the aupai-infra cut the transport verb lives in another
repository and cannot import them, and the contract
(`docs/standards/compute_contract.md`, 6e's ruling 3) says the project owns the schema and
publishes it as one small machine-readable file the infra repo reads. This writes that file.

WHAT IT IS NOT. Not a second key table. The lambdas stay the source of truth in this repo;
this file is their projection into data, and `--verify` proves the projection agrees with
them ON THE REAL LEDGERS rather than by inspection. A hand-maintained copy is exactly the
drift `pod_pull_ledgers.py:36` refuses ("a private key table would drift from the audit's,
and then two files would disagree about what a duplicate is") — the answer to that is not
"do not write the file", it is "generate it and check it".

THE KEY SPEC IS DATA, and it has to express what the lambdas do:

  ["name", "started"]                 tuple of two fields
  ["id"]                              single field
  [["ts", "at"], "reviewer", "task"]  a nested list is an OR -- first present, in order
  ["ckpt", ["profile", {"default": "full"}]]   a field with a default

That covers all nine. `friction.jsonl` needs the OR form three times in one key and
`score_matrix.jsonl` needs the default; neither is expressible without them, and a schema
that could not say them would silently key those two files differently from the audit.

    python3 scripts/gen_ledger_transport_schema.py            # write the file
    python3 scripts/gen_ledger_transport_schema.py --verify   # agree with KEYS on real rows
    python3 scripts/gen_ledger_transport_schema.py --selftest  # the resolver, known answers

# restartable: reads nine ledgers and writes one small JSON in a single call, seconds on a
# laptop with no card and no network. An interrupt leaves the previous file untouched and
# rerunning costs nothing, so there is no state to checkpoint.
"""
import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
OUT = os.path.join(ROOT, "data", "ledger_transport_schema.json")

# The key spec per ledger, in the data form above. Verified against ledger_audit.KEYS by
# --verify; the lambdas remain the source of truth and this is their projection.
SPEC = {
    "runs/experiments.jsonl": ["name", "started"],
    "runs/tasks.jsonl": ["id"],
    "runs/review.jsonl": [["ts", "at"], "reviewer", "task"],
    "runs/board.jsonl": ["ts", ["from", "who"]],
    "runs/milestones.jsonl": ["ckpt", "milestone"],
    "runs/score_matrix.jsonl": ["ckpt", {"field": "profile", "default": "full"}],
    "runs/retro.jsonl": [["owner", "id", "name"]],
    "runs/ledger_resolutions.jsonl": ["ledger", {"field": "key", "tuple_if_list": True}],
    "runs/friction.jsonl": [["when", "ts"], "who",
                            ["blocked_what", "what", "supersedes_cause"]],
}


def resolve(row, spec):
    """The key of `row` under `spec`. A single-element spec returns the bare value, not a
    1-tuple, because that is what the lambdas do -- tasks.jsonl keys on r.get("id"), and a
    reader comparing "abc" to ("abc",) finds every key missing."""
    parts = []
    for item in spec:
        if isinstance(item, list):
            # OR: the first field present, in order. `.get(f) or` and not `f in row`: the
            # lambdas use `or`, so an empty string falls through to the next name, and a
            # membership test would stop at it and key the row differently.
            v = None
            for f in item:
                v = row.get(f)
                if v:
                    break
            parts.append(v)
        elif isinstance(item, dict):
            v = row.get(item["field"], item.get("default"))
            if item.get("tuple_if_list") and isinstance(v, list):
                v = tuple(v)
            parts.append(v)
        else:
            parts.append(row.get(item))
    return parts[0] if len(parts) == 1 else tuple(parts)


def build():
    from ledger_audit import KEYS, PREDICATE, WRITE_STYLE

    missing = sorted(set(KEYS) - set(SPEC))
    assert not missing, (
        f"ledger_audit.KEYS has {missing} with no spec here. A ledger the transport verb "
        f"cannot key is one it would treat as unkeyed rows -- add the spec."
    )
    extra = sorted(set(SPEC) - set(KEYS))
    assert not extra, f"spec has {extra} which KEYS does not; the projection has drifted"

    return {
        "_comment": (
            "The transport verb's contract: which ledgers cross the boundary and what "
            "identifies a row. GENERATED by scripts/gen_ledger_transport_schema.py from "
            "scripts/ledger_audit.py -- edit that and regenerate, never this file. Distinct "
            "from data/ledger_schema.json, which describes memory_diag's FIELDS; this "
            "describes row IDENTITY for transport. Neither side may add a ledger without "
            "changing this file first (compute_contract.md, 6e ruling 3)."
        ),
        "version": 1,
        "key_spec_grammar": {
            "string": "a field name; its value is part of the key",
            "list": "OR -- the first of these fields with a truthy value, in order",
            "object": "{field, default?, tuple_if_list?} -- a field with a default, and/or "
                      "a list value tupled so it is hashable",
            "single_element": "a one-element spec yields the bare value, not a 1-tuple",
        },
        "ledgers": {
            rel: {
                "key": SPEC[rel],
                "write_style": WRITE_STYLE[rel],
                "predicate": PREDICATE[rel].__name__,
            }
            for rel in sorted(KEYS)
        },
    }


def verify(verbose=True):
    """The projection agrees with the lambdas ON THE REAL ROWS. Inspection is not enough:
    the OR forms and the default are exactly where a plausible-looking spec differs, and the
    difference only appears on rows that exercise them."""
    from ledger_audit import KEYS

    bad = 0
    for rel in sorted(KEYS):
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p):
            if verbose:
                print(f"  --   {rel}: absent, nothing to compare")
            continue
        rows = []
        with open(p, encoding="utf-8") as fh:
            for ln in fh:
                ln = ln.strip()
                if not ln:
                    continue
                try:
                    r = json.loads(ln)
                except json.JSONDecodeError:
                    continue  # pretty-printed blocks; _rows skips these too
                if isinstance(r, dict):
                    rows.append(r)
        diffs = [(i, KEYS[rel](r), resolve(r, SPEC[rel]))
                 for i, r in enumerate(rows)
                 if KEYS[rel](r) != resolve(r, SPEC[rel])]
        ok = not diffs
        bad += 0 if ok else 1
        if verbose:
            mark = "ok  " if ok else "BUG "
            print(f"  {mark} {rel}: {len(rows)} rows, {len(diffs)} disagreement(s)"
                  + ("" if ok else f" e.g. row {diffs[0][0]}: "
                                   f"audit={diffs[0][1]!r} spec={diffs[0][2]!r}"))
    return bad


def _selftest():
    """The resolver's forms, on rows built to exercise each. No ledger needed."""
    bad = 0
    cases = [
        ("two fields", {"name": "a", "started": "t"}, ["name", "started"], ("a", "t")),
        ("single is bare", {"id": "x"}, ["id"], "x"),
        ("OR takes the first present", {"at": "T", "reviewer": "r", "task": "k"},
         [["ts", "at"], "reviewer", "task"], ("T", "r", "k")),
        ("OR prefers the earlier name", {"ts": "A", "at": "B"}, [["ts", "at"]], "A"),
        # EMPTY FALLS THROUGH, because the lambdas use `or`. A membership test would stop at
        # the empty string and key this row ("", ...) where the audit keys it ("B", ...).
        ("OR skips an empty value", {"ts": "", "at": "B"}, [["ts", "at"]], "B"),
        ("default when absent", {"ckpt": "c"},
         ["ckpt", {"field": "profile", "default": "full"}], ("c", "full")),
        ("default not used when present", {"ckpt": "c", "profile": "p"},
         ["ckpt", {"field": "profile", "default": "full"}], ("c", "p")),
        ("list value is tupled", {"ledger": "L", "key": ["a", "b"]},
         ["ledger", {"field": "key", "tuple_if_list": True}], ("L", ("a", "b"))),
        ("missing field is None", {}, ["nope"], None),
    ]
    for name, row, spec, want in cases:
        got = resolve(row, spec)
        ok = got == want
        bad += 0 if ok else 1
        print(f"  {'ok  ' if ok else 'BUG '} {name}: {got!r}")

    # A tupled list must be HASHABLE, which is the whole reason for the form: an unhashable
    # key raises in any dict the transport builds, and a str() of it compares equal to
    # nothing another reader produces.
    try:
        hash(resolve({"ledger": "L", "key": ["a"]},
                     ["ledger", {"field": "key", "tuple_if_list": True}]))
        ok = True
    except TypeError:
        ok = False
    bad += 0 if ok else 1
    print(f"  {'ok  ' if ok else 'BUG '} a tupled list key is hashable")

    n = len(cases) + 1

    # EVERY SPEC FORM AGAINST ITS OWN LEDGER'S LAMBDA, on a synthetic row built to exercise
    # it. --verify cannot do this: it compares on the rows that exist, and a form no current
    # row reaches is unverified while reporting "0 disagreements". Measured 2026-09-05 --
    # deleting score_matrix's `default: full` changed the key of 0 of 69 rows, because every
    # row carries `profile` today. The first row written without one would key to None in
    # the infra repo and to "full" here, and the transport would call it a new key.
    from ledger_audit import KEYS
    probes = [
        ("runs/score_matrix.jsonl", {"ckpt": "c"}, "the default, on a row with no profile"),
        ("runs/friction.jsonl", {"ts": "T", "who": "w", "what": "x"},
         "both ORs' later alternatives"),
        ("runs/review.jsonl", {"at": "T", "reviewer": "r", "task": "k"},
         "the ts|at OR's later alternative"),
        ("runs/board.jsonl", {"ts": "T", "who": "w"}, "the from|who OR's later alternative"),
        ("runs/retro.jsonl", {"name": "n"}, "the owner|id|name OR's last alternative"),
        ("runs/ledger_resolutions.jsonl", {"ledger": "L", "key": ["a", "b"]},
         "the list-valued key"),
    ]
    for rel, row, what in probes:
        want, got = KEYS[rel](row), resolve(row, SPEC[rel])
        ok = want == got
        bad += 0 if ok else 1
        n += 1
        print(f"  {'ok  ' if ok else 'BUG '} {rel} exercises {what}: "
              f"{got!r}" + ("" if ok else f" but the audit says {want!r}"))

    print(f"gen_ledger_transport_schema selftest: {n - bad}/{n} pass")
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--verify", action="store_true",
                    help="compare the spec against ledger_audit.KEYS on the real ledgers")
    ap.add_argument("--check", action="store_true",
                    help="fail if the file on disk differs from what would be generated")
    a = ap.parse_args()
    if a.selftest:
        return _selftest()
    if a.verify:
        bad = verify()
        print(f"{'DISAGREES on ' + str(bad) + ' ledger(s)' if bad else 'agrees with KEYS'}")
        return 1 if bad else 0

    doc = build()
    text = json.dumps(doc, indent=2) + "\n"
    if a.check:
        if not os.path.exists(OUT):
            print(f"FAIL: {OUT} does not exist; run without --check", file=sys.stderr)
            return 1
        with open(OUT, encoding="utf-8") as fh:
            cur = fh.read()
        if cur != text:
            print(f"FAIL: {OUT} differs from the generated form -- ledger_audit.py changed "
                  f"and the schema was not regenerated", file=sys.stderr)
            return 1
        print(f"{OUT} matches ledger_audit.py")
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {OUT} ({len(doc['ledgers'])} ledgers)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
